- name: Installing Chromium browser and utils
  apt:
    name: 
      - xserver-xorg-video-all
      - xserver-xorg-input-all
      - xserver-xorg-core
      - xinit 
      - x11-xserver-utils 
      - chromium-browser
      - unclutter
    update_cache: yes
  become: true
