- name: Copying over bash_profile
  copy:
    src: ../files/.profile
    dest: /home/{{ username }}/.profile
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes
    mode: '0755'
    
- name: Copying over xinitrc
  copy:
    src: ../files/.xinitrc
    dest: /home/{{ username }}/.xinitrc
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes
    mode: '0755'
