---
- name: Updating apt cache
  apt:
    update_cache: yes

- name: Upgrade apt packages
  apt:
    upgrade: dist

- name: Finding out if reboot is required?
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required
    get_md5: false

- name: Reboot if kernel is updated
  reboot:
    msg: Reboot initiated by ansible due to kernel updates
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 0
    test_command: uptime
  when: reboot_required_file.stat.exists
